spring:
  datasource:
    # url: jdbc:h2:tcp://localhost/SpringBootDataJpaSample
    url: jdbc:h2:mem:sample
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
